name: Validate Chrome Integration

on:
  push:
  pull_request:

jobs:
  run-validation:
    name: Run Integration Tests with Latest Chrome
    runs-on: ubuntu-latest
    env:
      CHROME_BIN_PATH: /usr/bin/chromium

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download and install latest Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium

      - name: Run PDF generation integration test
        run: |
          python -m unittest process_report.tests.unit.test_chromium
